# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: checkout
    - uses: actions/checkout@v2
    - name: Setup pnpm
    - uses: pnpm/action-setup@v2.2.2
    - run: pnpm install
#       with:
 #      run_intall: pnpm install
     # If specified, run `pnpm install`
      
    
    - name: install Snyk
    - run: npm i -g snyk-pnpm-deptree-api-tool
    - run: npm i -g snyk
   # - run: snyk auth ${{ secrets.SNYK_TOKEN }}
    - run: snyk-pnpm-deptree-api-tool --root ./ -orgId snyk-policy-file-workshop --snykToken f40bf63f-ca18-44bc-a944-55bc80e34425

      #- name: install snyk-to-html
       # run: |
        #  npm install snyk-to-html -g
         # snyk test --json | snyk-to-html -o result.html
          #mkdir downloads
          # cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads
#      - name: Use the Upload Artifact GitHub Action
 #       uses: actions/upload-artifact@v2
  #      with:
   #       name: results
    #      path: downloads
